// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_stores.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveStore = `-- name: ApproveStore :one
UPDATE stores
SET status = 'approved', approved_at = now(), rejection_reason = NULL, updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status, rejection_reason, approved_at, created_at, updated_at
`

func (q *Queries) ApproveStore(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, approveStore, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsGfOriented,
		&i.OpeningHours,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'draft')
RETURNING id, ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status, rejection_reason, approved_at, created_at, updated_at
`

type CreateStoreParams struct {
	WardID       int32   `json:"ward_id"`
	Name         string  `json:"name"`
	Address      string  `json:"address"`
	Latitude     float64 `json:"latitude"`
	Longitude    float64 `json:"longitude"`
	IsGfOriented bool    `json:"is_gf_oriented"`
	OpeningHours []byte  `json:"opening_hours"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.WardID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.IsGfOriented,
		arg.OpeningHours,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsGfOriented,
		&i.OpeningHours,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status, rejection_reason, approved_at, created_at, updated_at FROM stores WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsGfOriented,
		&i.OpeningHours,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStoresByStatus = `-- name: ListStoresByStatus :many
SELECT s.id, s.ward_id, s.name, s.address, s.latitude, s.longitude, s.is_gf_oriented, s.opening_hours, s.status, s.rejection_reason, s.approved_at, s.created_at, s.updated_at, w.name_ja AS ward_name_ja, w.name_en AS ward_name_en
FROM stores s
JOIN wards w ON w.id = s.ward_id
WHERE s.status = $1
ORDER BY s.created_at DESC
`

type ListStoresByStatusRow struct {
	ID              uuid.UUID          `json:"id"`
	WardID          int32              `json:"ward_id"`
	Name            string             `json:"name"`
	Address         string             `json:"address"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	IsGfOriented    bool               `json:"is_gf_oriented"`
	OpeningHours    []byte             `json:"opening_hours"`
	Status          StoreStatus        `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	WardNameJa      string             `json:"ward_name_ja"`
	WardNameEn      string             `json:"ward_name_en"`
}

func (q *Queries) ListStoresByStatus(ctx context.Context, status StoreStatus) ([]ListStoresByStatusRow, error) {
	rows, err := q.db.Query(ctx, listStoresByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoresByStatusRow{}
	for rows.Next() {
		var i ListStoresByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.WardID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.IsGfOriented,
			&i.OpeningHours,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WardNameJa,
			&i.WardNameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectStore = `-- name: RejectStore :one
UPDATE stores
SET status = 'rejected', rejection_reason = $2, updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status, rejection_reason, approved_at, created_at, updated_at
`

type RejectStoreParams struct {
	ID              uuid.UUID   `json:"id"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

func (q *Queries) RejectStore(ctx context.Context, arg RejectStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, rejectStore, arg.ID, arg.RejectionReason)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsGfOriented,
		&i.OpeningHours,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitStore = `-- name: SubmitStore :one
UPDATE stores
SET status = 'pending', rejection_reason = NULL, updated_at = now()
WHERE id = $1 AND status IN ('draft', 'rejected')
RETURNING id, ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status, rejection_reason, approved_at, created_at, updated_at
`

// First submit or resubmit after rejection -> back to the review queue.
func (q *Queries) SubmitStore(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, submitStore, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsGfOriented,
		&i.OpeningHours,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStoreProfile = `-- name: UpdateStoreProfile :one
UPDATE stores
SET name           = $2,
    address        = $3,
    latitude       = $4,
    longitude      = $5,
    is_gf_oriented = $6,
    opening_hours  = $7,
    updated_at     = now()
WHERE id = $1
RETURNING id, ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status, rejection_reason, approved_at, created_at, updated_at
`

type UpdateStoreProfileParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Address      string    `json:"address"`
	Latitude     float64   `json:"latitude"`
	Longitude    float64   `json:"longitude"`
	IsGfOriented bool      `json:"is_gf_oriented"`
	OpeningHours []byte    `json:"opening_hours"`
}

func (q *Queries) UpdateStoreProfile(ctx context.Context, arg UpdateStoreProfileParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreProfile,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.IsGfOriented,
		arg.OpeningHours,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsGfOriented,
		&i.OpeningHours,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
