// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_menu.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (store_id, name, price_yen, image_url, gf_status, gf_note, sort_order, is_available)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, store_id, name, price_yen, image_url, gf_status, gf_note, sort_order, is_available, created_at, updated_at
`

type CreateMenuItemParams struct {
	StoreID     uuid.UUID   `json:"store_id"`
	Name        string      `json:"name"`
	PriceYen    int32       `json:"price_yen"`
	ImageUrl    pgtype.Text `json:"image_url"`
	GfStatus    GfStatus    `json:"gf_status"`
	GfNote      pgtype.Text `json:"gf_note"`
	SortOrder   int32       `json:"sort_order"`
	IsAvailable bool        `json:"is_available"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.StoreID,
		arg.Name,
		arg.PriceYen,
		arg.ImageUrl,
		arg.GfStatus,
		arg.GfNote,
		arg.SortOrder,
		arg.IsAvailable,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.PriceYen,
		&i.ImageUrl,
		&i.GfStatus,
		&i.GfNote,
		&i.SortOrder,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenuItem = `-- name: DeleteMenuItem :execrows
DELETE FROM menu_items WHERE id = $1 AND store_id = $2
`

type DeleteMenuItemParams struct {
	ID      uuid.UUID `json:"id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMenuItem, arg.ID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMenuItemsByStore = `-- name: ListMenuItemsByStore :many
SELECT id, store_id, name, price_yen, image_url, gf_status, gf_note, sort_order, is_available, created_at, updated_at FROM menu_items WHERE store_id = $1 ORDER BY sort_order, id
`

func (q *Queries) ListMenuItemsByStore(ctx context.Context, storeID uuid.UUID) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.PriceYen,
			&i.ImageUrl,
			&i.GfStatus,
			&i.GfNote,
			&i.SortOrder,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET name         = $3,
    price_yen    = $4,
    image_url    = $5,
    gf_status    = $6,
    gf_note      = $7,
    sort_order   = $8,
    is_available = $9,
    updated_at   = now()
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, name, price_yen, image_url, gf_status, gf_note, sort_order, is_available, created_at, updated_at
`

type UpdateMenuItemParams struct {
	ID          uuid.UUID   `json:"id"`
	StoreID     uuid.UUID   `json:"store_id"`
	Name        string      `json:"name"`
	PriceYen    int32       `json:"price_yen"`
	ImageUrl    pgtype.Text `json:"image_url"`
	GfStatus    GfStatus    `json:"gf_status"`
	GfNote      pgtype.Text `json:"gf_note"`
	SortOrder   int32       `json:"sort_order"`
	IsAvailable bool        `json:"is_available"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem,
		arg.ID,
		arg.StoreID,
		arg.Name,
		arg.PriceYen,
		arg.ImageUrl,
		arg.GfStatus,
		arg.GfNote,
		arg.SortOrder,
		arg.IsAvailable,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.PriceYen,
		&i.ImageUrl,
		&i.GfStatus,
		&i.GfNote,
		&i.SortOrder,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
