// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: internal_sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInternalSession = `-- name: CreateInternalSession :one
INSERT INTO internal_sessions (id, admin_id, refresh_token, user_agent, client_ip, is_blocked, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, admin_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type CreateInternalSessionParams struct {
	ID           uuid.UUID          `json:"id"`
	AdminID      uuid.UUID          `json:"admin_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInternalSession(ctx context.Context, arg CreateInternalSessionParams) (InternalSession, error) {
	row := q.db.QueryRow(ctx, createInternalSession,
		arg.ID,
		arg.AdminID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i InternalSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInternalSession = `-- name: DeleteInternalSession :execrows
DELETE FROM internal_sessions WHERE id = $1
`

// Revoke a single refresh session (logout).
func (q *Queries) DeleteInternalSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInternalSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInternalSessionsForAdmin = `-- name: DeleteInternalSessionsForAdmin :execrows
DELETE FROM internal_sessions WHERE admin_id = $1
`

// Revoke every refresh session for an admin, used after a password change or
// reset so sessions opened with the old password cannot be renewed.
func (q *Queries) DeleteInternalSessionsForAdmin(ctx context.Context, adminID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInternalSessionsForAdmin, adminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInternalSession = `-- name: GetInternalSession :one
SELECT id, admin_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at FROM internal_sessions WHERE id = $1
`

func (q *Queries) GetInternalSession(ctx context.Context, id uuid.UUID) (InternalSession, error) {
	row := q.db.QueryRow(ctx, getInternalSession, id)
	var i InternalSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
