// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: internal_stores.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStoresByNameWard = `-- name: CountStoresByNameWard :one
SELECT count(*) FROM stores WHERE lower(name) = lower($1) AND ward_id = $2
`

type CountStoresByNameWardParams struct {
	Lower  string `json:"lower"`
	WardID int32  `json:"ward_id"`
}

// Dedup helper for imports: is there already a store with this name in the ward?
// Makes re-running an import (or the future scraper) idempotent.
func (q *Queries) CountStoresByNameWard(ctx context.Context, arg CountStoresByNameWardParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStoresByNameWard, arg.Lower, arg.WardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStoreFull = `-- name: CreateStoreFull :one

INSERT INTO stores (
    ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours,
    status, cuisine, price_level, rating, review_count, nearest_station, blurb,
    gf_status, photo_url, name_en, phone, source_url, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20
)
RETURNING id, ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status, rejection_reason, approved_at, created_at, updated_at, cuisine, price_level, rating, review_count, nearest_station, blurb, gf_status, photo_url, name_en, phone, source_url, notes
`

type CreateStoreFullParams struct {
	WardID         int32       `json:"ward_id"`
	Name           string      `json:"name"`
	Address        string      `json:"address"`
	Latitude       float64     `json:"latitude"`
	Longitude      float64     `json:"longitude"`
	IsGfOriented   bool        `json:"is_gf_oriented"`
	OpeningHours   []byte      `json:"opening_hours"`
	Status         StoreStatus `json:"status"`
	Cuisine        string      `json:"cuisine"`
	PriceLevel     int32       `json:"price_level"`
	Rating         float32     `json:"rating"`
	ReviewCount    int32       `json:"review_count"`
	NearestStation string      `json:"nearest_station"`
	Blurb          string      `json:"blurb"`
	GfStatus       GfStatus    `json:"gf_status"`
	PhotoUrl       pgtype.Text `json:"photo_url"`
	NameEn         string      `json:"name_en"`
	Phone          string      `json:"phone"`
	SourceUrl      string      `json:"source_url"`
	Notes          string      `json:"notes"`
}

// Internal-operator store CRUD (/internal/stores). Unlike the store-admin
// self-serve queries in admin_stores.sql, these let an operator write every
// column on any store -- including the curated display fields (rating,
// review_count) and an explicit status -- so back-office staff can seed and
// correct restaurant entries directly.
// Operator create: populate every field, including an explicit status (e.g.
// seed a fully-curated store straight to 'approved').
func (q *Queries) CreateStoreFull(ctx context.Context, arg CreateStoreFullParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStoreFull,
		arg.WardID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.IsGfOriented,
		arg.OpeningHours,
		arg.Status,
		arg.Cuisine,
		arg.PriceLevel,
		arg.Rating,
		arg.ReviewCount,
		arg.NearestStation,
		arg.Blurb,
		arg.GfStatus,
		arg.PhotoUrl,
		arg.NameEn,
		arg.Phone,
		arg.SourceUrl,
		arg.Notes,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsGfOriented,
		&i.OpeningHours,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cuisine,
		&i.PriceLevel,
		&i.Rating,
		&i.ReviewCount,
		&i.NearestStation,
		&i.Blurb,
		&i.GfStatus,
		&i.PhotoUrl,
		&i.NameEn,
		&i.Phone,
		&i.SourceUrl,
		&i.Notes,
	)
	return i, err
}

const deleteStore = `-- name: DeleteStore :execrows
DELETE FROM stores WHERE id = $1
`

// Hard delete. menu_items and store_admins cascade via their FK ON DELETE
// CASCADE, so this removes the store and everything hanging off it.
func (q *Queries) DeleteStore(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStore, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listStoresMissingCoords = `-- name: ListStoresMissingCoords :many
SELECT id, ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status, rejection_reason, approved_at, created_at, updated_at, cuisine, price_level, rating, review_count, nearest_station, blurb, gf_status, photo_url, name_en, phone, source_url, notes FROM stores
WHERE latitude = 0 AND longitude = 0 AND address <> ''
ORDER BY created_at
LIMIT $1
`

// Geocode backfill queue: stores with an address but no coordinates yet
// (imports land at 0,0 because the CSV carries no lat/lng).
func (q *Queries) ListStoresMissingCoords(ctx context.Context, limit int32) ([]Store, error) {
	rows, err := q.db.Query(ctx, listStoresMissingCoords, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.WardID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.IsGfOriented,
			&i.OpeningHours,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Cuisine,
			&i.PriceLevel,
			&i.Rating,
			&i.ReviewCount,
			&i.NearestStation,
			&i.Blurb,
			&i.GfStatus,
			&i.PhotoUrl,
			&i.NameEn,
			&i.Phone,
			&i.SourceUrl,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreCoords = `-- name: UpdateStoreCoords :execrows
UPDATE stores SET latitude = $2, longitude = $3, updated_at = now()
WHERE id = $1
`

type UpdateStoreCoordsParams struct {
	ID        uuid.UUID `json:"id"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
}

func (q *Queries) UpdateStoreCoords(ctx context.Context, arg UpdateStoreCoordsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStoreCoords, arg.ID, arg.Latitude, arg.Longitude)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStoreFull = `-- name: UpdateStoreFull :one
UPDATE stores
SET ward_id         = $2,
    name            = $3,
    address         = $4,
    latitude        = $5,
    longitude       = $6,
    is_gf_oriented  = $7,
    opening_hours   = $8,
    status          = $9,
    -- Keep approved_at meaningful when an operator approves from the form
    -- rather than the Approve button: stamp it on the transition into
    -- 'approved', preserve the original date across later edits, and clear it
    -- if the store leaves 'approved'. Invariant: approved_at is set iff the
    -- store is currently approved.
    approved_at     = CASE
                          WHEN $9::store_status = 'approved' THEN COALESCE(approved_at, now())
                          ELSE NULL
                      END,
    cuisine         = $10,
    price_level     = $11,
    rating          = $12,
    review_count    = $13,
    nearest_station = $14,
    blurb           = $15,
    gf_status       = $16,
    photo_url       = $17,
    name_en         = $18,
    phone           = $19,
    source_url      = $20,
    notes           = $21,
    updated_at      = now()
WHERE id = $1
RETURNING id, ward_id, name, address, latitude, longitude, is_gf_oriented, opening_hours, status, rejection_reason, approved_at, created_at, updated_at, cuisine, price_level, rating, review_count, nearest_station, blurb, gf_status, photo_url, name_en, phone, source_url, notes
`

type UpdateStoreFullParams struct {
	ID             uuid.UUID   `json:"id"`
	WardID         int32       `json:"ward_id"`
	Name           string      `json:"name"`
	Address        string      `json:"address"`
	Latitude       float64     `json:"latitude"`
	Longitude      float64     `json:"longitude"`
	IsGfOriented   bool        `json:"is_gf_oriented"`
	OpeningHours   []byte      `json:"opening_hours"`
	Status         StoreStatus `json:"status"`
	Cuisine        string      `json:"cuisine"`
	PriceLevel     int32       `json:"price_level"`
	Rating         float32     `json:"rating"`
	ReviewCount    int32       `json:"review_count"`
	NearestStation string      `json:"nearest_station"`
	Blurb          string      `json:"blurb"`
	GfStatus       GfStatus    `json:"gf_status"`
	PhotoUrl       pgtype.Text `json:"photo_url"`
	NameEn         string      `json:"name_en"`
	Phone          string      `json:"phone"`
	SourceUrl      string      `json:"source_url"`
	Notes          string      `json:"notes"`
}

// Operator edit: overwrite every editable field on any store, regardless of
// its current status. status is passed explicitly so operators can move a
// store between states as part of an edit.
func (q *Queries) UpdateStoreFull(ctx context.Context, arg UpdateStoreFullParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreFull,
		arg.ID,
		arg.WardID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.IsGfOriented,
		arg.OpeningHours,
		arg.Status,
		arg.Cuisine,
		arg.PriceLevel,
		arg.Rating,
		arg.ReviewCount,
		arg.NearestStation,
		arg.Blurb,
		arg.GfStatus,
		arg.PhotoUrl,
		arg.NameEn,
		arg.Phone,
		arg.SourceUrl,
		arg.Notes,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsGfOriented,
		&i.OpeningHours,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cuisine,
		&i.PriceLevel,
		&i.Rating,
		&i.ReviewCount,
		&i.NearestStation,
		&i.Blurb,
		&i.GfStatus,
		&i.PhotoUrl,
		&i.NameEn,
		&i.Phone,
		&i.SourceUrl,
		&i.Notes,
	)
	return i, err
}
