// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: internal_admins.sql

package db

import (
	"context"
)

const createInternalAdmin = `-- name: CreateInternalAdmin :one
INSERT INTO internal_admins (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at
`

type CreateInternalAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateInternalAdmin(ctx context.Context, arg CreateInternalAdminParams) (InternalAdmin, error) {
	row := q.db.QueryRow(ctx, createInternalAdmin, arg.Email, arg.PasswordHash)
	var i InternalAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getInternalAdminByEmail = `-- name: GetInternalAdminByEmail :one
SELECT id, email, password_hash, created_at FROM internal_admins WHERE lower(email) = lower($1)
`

func (q *Queries) GetInternalAdminByEmail(ctx context.Context, lower string) (InternalAdmin, error) {
	row := q.db.QueryRow(ctx, getInternalAdminByEmail, lower)
	var i InternalAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
