// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listAvailableMenuItems = `-- name: ListAvailableMenuItems :many
SELECT id, store_id, name, price_yen, image_url, gf_status, gf_note, sort_order, is_available, created_at, updated_at FROM menu_items
WHERE store_id = $1 AND is_available = true
ORDER BY sort_order, id
`

func (q *Queries) ListAvailableMenuItems(ctx context.Context, storeID uuid.UUID) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listAvailableMenuItems, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.PriceYen,
			&i.ImageUrl,
			&i.GfStatus,
			&i.GfNote,
			&i.SortOrder,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
