// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stores.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getApprovedStore = `-- name: GetApprovedStore :one
SELECT s.id, s.ward_id, s.name, s.address, s.latitude, s.longitude, s.is_gf_oriented, s.opening_hours, s.status, s.rejection_reason, s.approved_at, s.created_at, s.updated_at, w.name_ja AS ward_name_ja, w.name_en AS ward_name_en
FROM stores s
JOIN wards w ON w.id = s.ward_id
WHERE s.id = $1 AND s.status = 'approved'
`

type GetApprovedStoreRow struct {
	ID              uuid.UUID          `json:"id"`
	WardID          int32              `json:"ward_id"`
	Name            string             `json:"name"`
	Address         string             `json:"address"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	IsGfOriented    bool               `json:"is_gf_oriented"`
	OpeningHours    []byte             `json:"opening_hours"`
	Status          StoreStatus        `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	WardNameJa      string             `json:"ward_name_ja"`
	WardNameEn      string             `json:"ward_name_en"`
}

func (q *Queries) GetApprovedStore(ctx context.Context, id uuid.UUID) (GetApprovedStoreRow, error) {
	row := q.db.QueryRow(ctx, getApprovedStore, id)
	var i GetApprovedStoreRow
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsGfOriented,
		&i.OpeningHours,
		&i.Status,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WardNameJa,
		&i.WardNameEn,
	)
	return i, err
}

const listApprovedStores = `-- name: ListApprovedStores :many
SELECT s.id, s.ward_id, s.name, s.address, s.latitude, s.longitude, s.is_gf_oriented, s.opening_hours, s.status, s.rejection_reason, s.approved_at, s.created_at, s.updated_at, w.name_ja AS ward_name_ja, w.name_en AS ward_name_en
FROM stores s
JOIN wards w ON w.id = s.ward_id
WHERE s.status = 'approved'
  AND ($1::int IS NULL OR s.ward_id = $1)
  AND s.id > $2
ORDER BY s.id
LIMIT $3
`

type ListApprovedStoresParams struct {
	WardID    pgtype.Int4 `json:"ward_id"`
	Cursor    uuid.UUID   `json:"cursor"`
	PageLimit int32       `json:"page_limit"`
}

type ListApprovedStoresRow struct {
	ID              uuid.UUID          `json:"id"`
	WardID          int32              `json:"ward_id"`
	Name            string             `json:"name"`
	Address         string             `json:"address"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	IsGfOriented    bool               `json:"is_gf_oriented"`
	OpeningHours    []byte             `json:"opening_hours"`
	Status          StoreStatus        `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	WardNameJa      string             `json:"ward_name_ja"`
	WardNameEn      string             `json:"ward_name_en"`
}

// Keyset pagination over approved stores, ordered by id. Pass the zero UUID
// (00000000-...) as @cursor for the first page; it is less than every real id,
// so `id > @cursor` returns from the start. Optional ward filter via @ward_id.
func (q *Queries) ListApprovedStores(ctx context.Context, arg ListApprovedStoresParams) ([]ListApprovedStoresRow, error) {
	rows, err := q.db.Query(ctx, listApprovedStores, arg.WardID, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedStoresRow{}
	for rows.Next() {
		var i ListApprovedStoresRow
		if err := rows.Scan(
			&i.ID,
			&i.WardID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.IsGfOriented,
			&i.OpeningHours,
			&i.Status,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WardNameJa,
			&i.WardNameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
