// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_admins.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStoreAdmin = `-- name: CreateStoreAdmin :one
INSERT INTO store_admins (store_id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, store_id, email, password_hash, created_at, updated_at
`

type CreateStoreAdminParams struct {
	StoreID      uuid.UUID `json:"store_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateStoreAdmin(ctx context.Context, arg CreateStoreAdminParams) (StoreAdmin, error) {
	row := q.db.QueryRow(ctx, createStoreAdmin, arg.StoreID, arg.Email, arg.PasswordHash)
	var i StoreAdmin
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreAdminByEmail = `-- name: GetStoreAdminByEmail :one
SELECT id, store_id, email, password_hash, created_at, updated_at FROM store_admins WHERE lower(email) = lower($1)
`

func (q *Queries) GetStoreAdminByEmail(ctx context.Context, lower string) (StoreAdmin, error) {
	row := q.db.QueryRow(ctx, getStoreAdminByEmail, lower)
	var i StoreAdmin
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreAdminByID = `-- name: GetStoreAdminByID :one
SELECT id, store_id, email, password_hash, created_at, updated_at FROM store_admins WHERE id = $1
`

func (q *Queries) GetStoreAdminByID(ctx context.Context, id uuid.UUID) (StoreAdmin, error) {
	row := q.db.QueryRow(ctx, getStoreAdminByID, id)
	var i StoreAdmin
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
