// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription_receipts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getReceiptByOriginalTxID = `-- name: GetReceiptByOriginalTxID :one
SELECT id, user_id, original_tx_id, product_id, environment, status, expires_at, created_at, updated_at FROM subscription_receipts WHERE original_tx_id = $1
`

func (q *Queries) GetReceiptByOriginalTxID(ctx context.Context, originalTxID string) (SubscriptionReceipt, error) {
	row := q.db.QueryRow(ctx, getReceiptByOriginalTxID, originalTxID)
	var i SubscriptionReceipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalTxID,
		&i.ProductID,
		&i.Environment,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubscriptionReceipt = `-- name: UpsertSubscriptionReceipt :one
INSERT INTO subscription_receipts (user_id, original_tx_id, product_id, environment, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (original_tx_id) DO UPDATE
SET product_id  = EXCLUDED.product_id,
    environment = EXCLUDED.environment,
    status      = EXCLUDED.status,
    expires_at  = EXCLUDED.expires_at,
    updated_at  = now()
RETURNING id, user_id, original_tx_id, product_id, environment, status, expires_at, created_at, updated_at
`

type UpsertSubscriptionReceiptParams struct {
	UserID       uuid.UUID               `json:"user_id"`
	OriginalTxID string                  `json:"original_tx_id"`
	ProductID    string                  `json:"product_id"`
	Environment  SubscriptionEnvironment `json:"environment"`
	Status       ReceiptStatus           `json:"status"`
	ExpiresAt    pgtype.Timestamptz      `json:"expires_at"`
}

// One row per original transaction. Both /subscription/verify and the Apple
// webhook converge on this so the latest state always wins.
func (q *Queries) UpsertSubscriptionReceipt(ctx context.Context, arg UpsertSubscriptionReceiptParams) (SubscriptionReceipt, error) {
	row := q.db.QueryRow(ctx, upsertSubscriptionReceipt,
		arg.UserID,
		arg.OriginalTxID,
		arg.ProductID,
		arg.Environment,
		arg.Status,
		arg.ExpiresAt,
	)
	var i SubscriptionReceipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalTxID,
		&i.ProductID,
		&i.Environment,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
