// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, apple_user_id)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, apple_user_id, subscription_status, sub_expires_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	AppleUserID  pgtype.Text `json:"apple_user_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.AppleUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.SubscriptionStatus,
		&i.SubExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAppleID = `-- name: GetUserByAppleID :one
SELECT id, email, password_hash, apple_user_id, subscription_status, sub_expires_at, created_at, updated_at FROM users WHERE apple_user_id = $1
`

func (q *Queries) GetUserByAppleID(ctx context.Context, appleUserID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAppleID, appleUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.SubscriptionStatus,
		&i.SubExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, apple_user_id, subscription_status, sub_expires_at, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.SubscriptionStatus,
		&i.SubExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, apple_user_id, subscription_status, sub_expires_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.SubscriptionStatus,
		&i.SubExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE users
SET subscription_status = $2,
    sub_expires_at      = $3,
    updated_at          = now()
WHERE id = $1
RETURNING id, email, password_hash, apple_user_id, subscription_status, sub_expires_at, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID                 uuid.UUID          `json:"id"`
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	SubExpiresAt       pgtype.Timestamptz `json:"sub_expires_at"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (User, error) {
	row := q.db.QueryRow(ctx, updateSubscription, arg.ID, arg.SubscriptionStatus, arg.SubExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.SubscriptionStatus,
		&i.SubExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
