// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wards.sql

package db

import (
	"context"
)

const getWard = `-- name: GetWard :one
SELECT id, name_ja, name_en FROM wards WHERE id = $1
`

func (q *Queries) GetWard(ctx context.Context, id int32) (Ward, error) {
	row := q.db.QueryRow(ctx, getWard, id)
	var i Ward
	err := row.Scan(&i.ID, &i.NameJa, &i.NameEn)
	return i, err
}

const listWards = `-- name: ListWards :many
SELECT id, name_ja, name_en FROM wards ORDER BY id
`

func (q *Queries) ListWards(ctx context.Context) ([]Ward, error) {
	rows, err := q.db.Query(ctx, listWards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ward{}
	for rows.Next() {
		var i Ward
		if err := rows.Scan(&i.ID, &i.NameJa, &i.NameEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
